version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    command: npm run both
#    command: http-server dist --port 80
    ports:
      - "3004:3004"
      - "8080:8080"